

 ######################## CZASY ZAŁĄCZONYCH ELEMENTÓW ########################
 
 # UPS
- platform: history_stats
  name: ups time_on
  entity_id: binary_sensor.alwaystrue
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

# PLC
- platform: history_stats
  name: plc time_on
  entity_id: binary_sensor.alwaystrue
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

# ODKURZACZ ROBOROCK
- platform: history_stats
  name: roborock time_on
  entity_id: binary_sensor.ping_roborock
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

 # GNIAZDKO MONITOR 
- platform: history_stats
  name: Monitor_hmi Time_ON
  entity_id: switch.gniazdkomonitor_ha
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

 # GNIAZDKO LAPTOPA  BIURO
- platform: history_stats
  name: biuro laptop Time_ON
  entity_id: switch.gniazdkobiuro_laptop
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

 # GNIAZDKO LAPTOPA JULIA
- platform: history_stats
  name: julia laptop Time_ON
  entity_id: switch.gniazdkojulia_laptop
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

 # GNIAZDKO LAPTOPA  OLIWIA
- platform: history_stats
  name: oliwia laptop Time_ON
  entity_id: switch.gniazdkooliwia_laptop
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
  
 # PRALKA1
- platform: history_stats
  name: pralnia_pralka1 time_on
  entity_id: sensor.pranie1
  state: 'Trwa pranie...'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
 # PRALKA2
- platform: history_stats
  name: pralnia_pralka2 time_on
  entity_id: sensor.pranie2
  state: 'Trwa pranie...'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
 # SUSZARKA
- platform: history_stats
  name: pralnia_suszarka time_on
  entity_id: sensor.suszarka_stan
  state: 'Trwa suszenie...'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

 # ZMYWARKA
- platform: history_stats
  name: kuchnia_zmywarka time_on
  entity_id: sensor.zmywarka
  state: 'Trwa mycie...'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

 # PAZNOKCIE
- platform: history_stats
  name: gabinet paznokcie time_on
  entity_id: switch.gniazdkogabinet_paznokcie
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

# LODÓWKA
- platform: history_stats
  name: kuchnia_lodowka time_on
  entity_id: switch.gniazdkokuchnia_lodowka
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

# SALON MEDIA
- platform: history_stats
  name: salon_media time_on
  entity_id: switch.gniazdka_tv_salon
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
 
# GNIAZDKA PIEKARNIK
- platform: history_stats
  name: kuchnia_piekarnik time_on
  entity_id: sensor.piekarnik
  state: 'Włączony'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

# GNIAZDKA MIKROFALOWKA
- platform: history_stats
  name: kuchnia_mikrofalowka time_on
  entity_id: sensor.mikrofalowka
  state: 'Włączona'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

# BOILER CO
- platform: history_stats
  name: kotlownia_piec time_on
  entity_id: switch.kotlownia_piec
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

# BIURO ŻELAZKO
- platform: history_stats
  name: biuro_zelazko_time_on
  entity_id: sensor.zelazko
  state: 'Prasowanie'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

# DISKSTATION
- platform: history_stats
  name: diskstation time_on
  entity_id: button.diskstation_reboot
  state: 'unknown'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

# REJESTRATOR
- platform: history_stats
  name: Rejestrator time_on
  entity_id: binary_sensor.binary_rejestrator
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

# GNIAZDKA BASEN
- platform: history_stats
  name: basen_filtr time_on
  entity_id: switch.gniazdka_zewnetrzne
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: basen_filtr count_on
  entity_id: switch.gniazdka_zewnetrzne
  state: 'on'
  type: count
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

# GNIAZDKA BASEN DOGRZEWACZ
- platform: history_stats
  name: basen_dogrzewacz time_on
  entity_id: switch.basen_dogrzewacz
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: basen_dogrzewacz count_on
  entity_id: switch.basen_dogrzewacz
  state: 'on'
  type: count
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

# GNIAZDKA SALON TV
- platform: history_stats
  name: salon_tv time_on
  entity_id: switch.gniazdka_tv_salon
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: salon_tv count_on
  entity_id: switch.gniazdka_tv_salon
  state: 'on'
  type: count
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

# STRYCH, WZMACNIACZ ANTENOWY
- platform: history_stats
  name: attic time_on
  entity_id: switch.gniazdka_strych
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: attic count_on
  entity_id: switch.gniazdka_strych
  state: 'on'
  type: count
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

# ZANIKI NAPIĘCIA
- platform: history_stats
  name: no_power time_on
  entity_id: binary_sensor.zasilanie_230v_ok
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: no_power count_on
  entity_id: binary_sensor.zasilanie_230v_ok
  state: 'on'
  type: count
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
