
######################## AKTYWNOŚĆ MULTIMEDIÓW ########################

- platform: history_stats
  name: Czas TV w salonie
  entity_id: media_player.salon_philips
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: Ilość TV w salonie
  entity_id: media_player.salon_philips
  state: 'on'
  type: count
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}' 

- platform: history_stats
  name: Czas music w salonie
  entity_id: media_player.salon_music
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: Ilość music w salonie
  entity_id: media_player.salon_music
  state: 'on'
  type: count
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}' 