
######################## CZASY PIECA CO ########################

- platform: history_stats
  name: co_piec_grzanie Time_ON
  entity_id: binary_sensor.piec_co_dziala
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: co_piec_grzanie Count_ON
  entity_id: binary_sensor.piec_co_dziala
  state: 'on'
  type: count
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

######################## CZASY POMPY CWU ########################

- platform: history_stats
  name: ogrzewanie_cwu_vaillant Time_ON
  entity_id: binary_sensor.ogrzewanie_cwu_vaillant
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: ogrzewanie_cwu_vaillant Count_ON
  entity_id: binary_sensor.ogrzewanie_cwu_vaillant
  state: 'on'
  type: count
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: ogrzewanie_cwu_plc Time_ON
  entity_id: binary_sensor.ogrzewanie_cwu_plc
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: ogrzewanie_cwu_plc Count_ON
  entity_id: binary_sensor.ogrzewanie_cwu_plc
  state: 'on'
  type: count
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

######################## CZASY CYRKULACJA POMPA ########################

- platform: history_stats
  name: cwu_pompa_cyrkulacji Time_ON
  entity_id: binary_sensor.pompa_cyrkulacji
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: cwu_pompa_cyrkulacji Count_ON
  entity_id: binary_sensor.pompa_cyrkulacji
  state: 'on'
  type: count
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: cwu_pompa_cyrkulacji_wymuszenie Time_ON
  entity_id: switch.pompa_cyrkulacji_wymuszenie
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: cwu_pompa_cyrkulacji_wymuszenie Count_ON
  entity_id: switch.pompa_cyrkulacji_wymuszenie
  state: 'on'
  type: count
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

######################## CZASY ZAŁĄCZONYCH DOGRZEWACZY ########################

- platform: history_stats
  name: co_dogrzewacz_1_time_on
  entity_id: switch.kotlownia_dogrzewacz_1
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: co_dogrzewacz_1_count_on
  entity_id: switch.kotlownia_dogrzewacz_1
  state: 'on'
  type: count
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: co_dogrzewacz_2_time_on
  entity_id: switch.kotlownia_dogrzewacz_2
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: co_dogrzewacz_2_count_on
  entity_id: switch.kotlownia_dogrzewacz_2
  state: 'on'
  type: count
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

######################## CZASY ZAŁĄCZONYCH GZEJNIKÓW ELEKTRYCZNYCH ########################

- platform: history_stats
  name: co_grzejnik_lazienkadolna_time_on
  entity_id: switch.kaloryfer_lazienka_dolna
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: co_grzejnik_lazienkadolna_count_on
  entity_id: switch.kaloryfer_lazienka_dolna
  state: 'on'
  type: count
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: co_grzejnik_lazienkagorna_time_on
  entity_id: switch.kaloryfer_lazienka_gorna
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: co_grzejnik_lazienkagorna_count_on
  entity_id: switch.kaloryfer_lazienka_gorna
  state: 'on'
  type: count
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

######################## CZASY ZAŁĄCZONEJ PODŁOGÓWKI ########################

- platform: history_stats
  name: ogrzewanie_parter Time_ON
  entity_id: binary_sensor.ogrzewanie_parter
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: ogrzewanie_parter Count_ON
  entity_id: binary_sensor.ogrzewanie_parter
  state: 'on'
  type: count
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}' 

- platform: history_stats
  name: ogrzewanie_pietro Time_ON
  entity_id: binary_sensor.ogrzewanie_pietro
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: ogrzewanie_pietro Count_ON
  entity_id: binary_sensor.ogrzewanie_pietro
  state: 'on'
  type: count
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}' 

######################## CZASY ZAŁĄCZONEJ PODŁOGÓWKI  POMIESZCZENIA ########################

- platform: history_stats
  name: co_entrance Time_ON
  entity_id: binary_sensor.co_entrance
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: co_bathroom_down Time_ON
  entity_id: binary_sensor.co_bathroom_down
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: co_smallroom Time_ON
  entity_id: binary_sensor.co_smallroom
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: co_pantry Time_ON
  entity_id: binary_sensor.co_pantry
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: co_boiler Time_ON
  entity_id: binary_sensor.co_boiler
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: co_garage Time_ON
  entity_id: binary_sensor.co_garage
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: co_badroom Time_ON
  entity_id: binary_sensor.co_badroom
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: co_julia Time_ON
  entity_id: binary_sensor.co_julia
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: co_oliwia Time_ON
  entity_id: binary_sensor.co_oliwia
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: co_office Time_ON
  entity_id: binary_sensor.co_office
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: co_washroom Time_ON
  entity_id: binary_sensor.co_washroom
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
