
######################## POMIAR PRĄDU I NAPIĘCIA ########################

 ############# PODSUMOWANIA RACHUNKU #############

- platform: ads
  name: Prąd Rachunek Aktualnie
  adsvar: GVL_Power_HA.iPradRachunekAktualnie
  unit_of_measurement: 'zł'
  factor: 100
  adstype: dint

###################### BIEŻACE UŻYCIE ######################

- platform: ads
  name: Zużycie pradu dziś          ## zuzycie prądu dziś
  adsvar: GVL_Power_HA.iPradUzycieDzis
  unit_of_measurement: 'kWh'
  factor: 100
  adstype: dint

- platform: ads
  name: Koszt pradu dziś          ## koszt prądu dziś
  adsvar: GVL_Power_HA.iPradUzycieDzisiejszeKoszt
  unit_of_measurement: 'zł'
  factor: 100
  adstype: int

- platform: ads
  name: Zużycie pradu Miesiac          ## zuzycie prądu Miesiąc
  adsvar: GVL_Power_HA.iPradUzycieMiesiac
  unit_of_measurement: 'kWh'
  factor: 100
  adstype: dint

- platform: ads
  name: Licznik główny prądu                ## główna wartośćlicznika prądu
  adsvar: GVL_Power_HA.iPowerLicznikTERAZ
  unit_of_measurement: 'kWh'
  factor: 100
  adstype: dint

- platform: ads
  name: Zużycie pradu ZeszlyMiesiac          ## zuzycie prądu ZeszłyMiesiąc
  adsvar: GVL_Power_HA.iPradUzycieZeszlyMiesiac
  unit_of_measurement: 'kWh'
  factor: 100
  adstype: dint

- platform: ads
  name: Koszt pradu w zeszłym miesiącu          ## koszt prądu w zeszłym miesiącu
  adsvar: GVL_Power_HA.iPradRachunekZeszlyMiesiac
  unit_of_measurement: 'zł'
  factor: 100
  adstype: dint

- platform: ads
  name: Licznik główny prądu zeszły miesiac ## główna wartość licznika prądu z zeszłego miesiąca
  adsvar: GVL_Power_HA.iPowerLicznikZeszlyMiesiac
  unit_of_measurement: 'kWh'
  adstype: dint

- platform: ads
  name: Cena pradu                          ## aktualna cena za kWh prądu
  adsvar: GVL_Power_HA.iPower_koszt
  unit_of_measurement: 'zł/kWh'
  factor: 100
  adstype: int

- platform: ads
  name: Cena sprzedazy pradu                ## aktualna cena za kWh prądu
  adsvar: GVL_Power_HA.iCenaSprzedaz1kW
  unit_of_measurement: 'zł/kWh'
  factor: 100
  adstype: int

- platform: ads
  name: Sprzedaz pradu na godzine           ## bierzący koszt prądu wg aktualnego zużycia
  adsvar: GVL_Power_HA.iChwilowaSprzedazPradu
  unit_of_measurement: 'zł'
  factor: 100
  adstype: int

- platform: ads
  name: Koszt pradu na godzine              ## bierzący koszt prądu wg aktualnego zużycia
  adsvar: GVL_Power_HA.iChwilowyKosztPradu
  unit_of_measurement: 'zł'
  factor: 100
  adstype: int


######################## PODZIAŁ NA FAZY ########################

- platform: ads
  name: Voltage_L1
  adsvar: P_Power.iVoltage_L1
  unit_of_measurement: 'V'
  factor: 10
  adstype: int
- platform: ads
  name: Voltage_L2
  adsvar: P_Power.iVoltage_L2
  unit_of_measurement: 'V'
  factor: 10
  adstype: int
- platform: ads
  name: Voltage_L3
  adsvar: P_Power.iVoltage_L3
  unit_of_measurement: 'V'
  factor: 10
  adstype: int
- platform: ads
  name: Voltage_PV_L1
  adsvar: P_Power.iVoltage_PV_L1
  unit_of_measurement: 'V'
  factor: 10
  adstype: int
- platform: ads
  name: Voltage_PV_L2
  adsvar: P_Power.iVoltage_PV_L2
  unit_of_measurement: 'V'
  factor: 10
  adstype: int
- platform: ads
  name: Voltage_PV_L3
  adsvar: P_Power.iVoltage_PV_L3
  unit_of_measurement: 'V'
  factor: 10
  adstype: int

- platform: ads
  name: iPower_L1
  adsvar: P_Power.iPower_L1
  unit_of_measurement: 'W'
  factor: 1
  adstype: int
- platform: ads
  name: iPower_L2
  adsvar: P_Power.iPower_L2
  unit_of_measurement: 'W'
  factor: 1
  adstype: int
- platform: ads
  name: iPower_L3
  adsvar: P_Power.iPower_L3
  unit_of_measurement: 'W'
  factor: 1
  adstype: int

- platform: ads
  name: iPower_PV_L1
  adsvar: P_Power.iPower_PV_L1
  unit_of_measurement: 'W'
  factor: 1
  adstype: int
- platform: ads
  name: iPower_PV_L2
  adsvar: P_Power.iPower_PV_L2
  unit_of_measurement: 'W'
  factor: 1
  adstype: int
- platform: ads
  name: iPower_PV_L3
  adsvar: P_Power.iPower_PV_L3
  unit_of_measurement: 'W'
  factor: 1
  adstype: int

- platform: ads
  name: iPower_L1_OUT
  adsvar: P_Power.iPower_L1_OUT
  unit_of_measurement: 'W'
  factor: 1
  adstype: int
- platform: ads
  name: iPower_L2_OUT
  adsvar: P_Power.iPower_L2_OUT
  unit_of_measurement: 'W'
  factor: 1
  adstype: int
- platform: ads
  name: iPower_L3_OUT
  adsvar: P_Power.iPower_L3_OUT
  unit_of_measurement: 'W'
  factor: 1
  adstype: int

- platform: ads
  name: iPower_L1_full
  adsvar: P_Power.iPower_L1_full
  unit_of_measurement: 'W'
  factor: 1
  adstype: int
- platform: ads
  name: iPower_L2_full
  adsvar: P_Power.iPower_L2_full
  unit_of_measurement: 'W'
  factor: 1
  adstype: int
- platform: ads
  name: iPower_L3_full
  adsvar: P_Power.iPower_L3_full
  unit_of_measurement: 'W'
  factor: 1
  adstype: int

- platform: ads
  name: iCurrent_L1
  adsvar: P_Power.iCurrent_L1
  unit_of_measurement: 'A'
  factor: 10
  adstype: int
- platform: ads
  name: iCurrent_L2
  adsvar: P_Power.iCurrent_L2
  unit_of_measurement: 'A'
  factor: 10
  adstype: int
- platform: ads
  name: iCurrent_L3
  adsvar: P_Power.iCurrent_L3
  unit_of_measurement: 'A'
  factor: 10
  adstype: int

- platform: ads
  name: iCurrent_PV_L1
  adsvar: P_Power.iCurrent_PV_L1
  unit_of_measurement: 'A'
  factor: 10
  adstype: int
- platform: ads
  name: iCurrent_PV_L2
  adsvar: P_Power.iCurrent_PV_L2
  unit_of_measurement: 'A'
  factor: 10
  adstype: int
- platform: ads
  name: iCurrent_PV_L3
  adsvar: P_Power.iCurrent_PV_L3
  unit_of_measurement: 'A'
  factor: 10
  adstype: int

- platform: ads
  name: iEnergy_L1
  adsvar: P_Power.iEnergy_L1
  unit_of_measurement: 'kWh'
  factor: 10
  adstype: int
- platform: ads
  name: iEnergy_L2
  adsvar: P_Power.iEnergy_L2
  unit_of_measurement: 'kWh'
  factor: 10
  adstype: int
- platform: ads
  name: iEnergy_L3
  adsvar: P_Power.iEnergy_L3
  unit_of_measurement: 'kWh'
  factor: 10
  adstype: int
  
- platform: ads
  name: iEnergy_PV_L1
  adsvar: P_Power.iEnergy_PV_L1
  unit_of_measurement: 'kWh'
  factor: 10
  adstype: int
- platform: ads
  name: iEnergy_PV_L2
  adsvar: P_Power.iEnergy_PV_L2
  unit_of_measurement: 'kWh'
  factor: 10
  adstype: int
- platform: ads
  name: iEnergy_PV_L3
  adsvar: P_Power.iEnergy_PV_L3
  unit_of_measurement: 'kWh'
  factor: 10
  adstype: int

- platform: ads
  name: iCosFi_L1
  adsvar: P_Power.icosfi_L1
  unit_of_measurement: 'fi'
  factor: 100
  adstype: int
- platform: ads
  name: iCosFi_L2
  adsvar: P_Power.icosfi_L2
  unit_of_measurement: 'fi'
  factor: 100
  adstype: int
- platform: ads
  name: iCosFi_L3
  adsvar: P_Power.icosfi_L3
  unit_of_measurement: 'fi'
  factor: 100
  adstype: int

- platform: ads
  name: iCurrent_SUM
  adsvar: P_Power.iCurrent_SUM
  unit_of_measurement: 'A'
  factor: 10
  adstype: int
- platform: ads
  name: iCurrent_PV_SUM
  adsvar: P_Power.iCurrent_PV_SUM
  unit_of_measurement: 'A'
  factor: 10
  adstype: int
  
- platform: ads
  name: iEnergy_SUM
  adsvar: P_Power.iEnergy_SUM
  unit_of_measurement: 'kWh'
  factor: 10
  adstype: int
- platform: ads
  name: iEnergy_PV_SUM
  adsvar: P_Power.iEnergy_PV_SUM
  unit_of_measurement: 'kWh'
  factor: 10
  adstype: int

############# PRĄD CAŁKOWITY #############
- platform: ads
  name: iPower_SUM_FULL         # wartość pełna + i - 
  adsvar: P_Power.iPower_SUM_FULL
  unit_of_measurement: 'W'
  adstype: int
  
############# PRĄD KUPOWANY Z SIECI #############
- platform: ads
  name: iPower_SUM
  adsvar: P_Power.iPower_SUM    # kupno prądu z sieci
  unit_of_measurement: 'W'
  adstype: int

############# PRĄD ODDAWANY DO SIECI #############
- platform: ads
  name: iPower_PV_SUM
  adsvar: P_Power.iPower_PV_SUM # produkcja prądu z paneli
  unit_of_measurement: 'W'
  adstype: int

############# PRĄD SPRZEDAWANY Z SIECI #############
- platform: ads
  name: iPower_NoPV_SUM
  adsvar: P_Power.iPower_NoPV_SUM # sprzedaż prądu do sieci
  unit_of_measurement: 'W'
  adstype: int

############# PRĄD ZBINALNSOWANY #############
- platform: ads
  name: iPower_kupno_bilans
  adsvar: P_Power.iPower_kupno_bilans
  unit_of_measurement: 'W'
  adstype: int

- platform: ads
  name: iPower_sprzedaz_bilans
  adsvar: P_Power.iPower_sprzedaz_bilans
  unit_of_measurement: 'W'
  adstype: int

- platform: ads
  name: Prad ilosc obliczen   ## ilość wykonanych obliczeń w ciągu dnia
  adsvar: P_PowerMeter.iPradCalc
  adstype: int

############# ILOŚĆ PRZERWAŃ ZASILANIA 24VDC #############

- platform: ads
  name: Ilosc przerwac zasilania DC   ## ilość wykonanych obliczeń w ciągu dnia
  adsvar: GVL_Power.ilosc_przerwan_24v
  adstype: int

- platform: ads
  name: Ilosc przerwac zasilania DC P0   ## ilość wykonanych obliczeń w ciągu dnia
  adsvar: P_Power.iBezpiecznikiP0
  adstype: int
- platform: ads
  name: Ilosc przerwac zasilania DC P1   ## ilość wykonanych obliczeń w ciągu dnia
  adsvar: P_Power.iBezpiecznikiP1
  adstype: int