
######################## POZYCJA SŁOŃCA ########################

- platform: ads
  name: Slonce elevation
  adsvar: P_Zaluzje.SunElevation
  adstype: int
  unit_of_measurement: '°'
  factor: 100 
- platform: ads
  name: Slonce azimuth
  adsvar: P_Zaluzje.SunAzimuth
  adstype: int
  unit_of_measurement: '°'
  factor: 100
  
  
######################## LIFEBIT ########################

- platform: ads
  name: LifeBit PLC
  adsvar: P_System.iLicznik
  adstype: int

######################## PRZEKROCZONE LICZNIKI I BŁĘDY ########################

- platform: ads
  name: dCheckBounds
  adsvar: GVL_Checks.dCheckBounds
  adstype: dint
- platform: ads
  name: dCheckDivDInt
  adsvar: GVL_Checks.dCheckDivDInt
  adstype: dint
- platform: ads
  name: dCheckDivLInt
  adsvar: GVL_Checks.dCheckDivLInt
  adstype: dint
- platform: ads
  name: dCheckDivLReal
  adsvar: GVL_Checks.dCheckDivLReal
  adstype: dint
- platform: ads
  name: dCheckDivReal
  adsvar: GVL_Checks.dCheckDivReal
  adstype: dint
- platform: ads
  name: dCheckRangeSigned
  adsvar: GVL_Checks.dCheckRangeSigned
  adstype: dint
- platform: ads
  name: dCheckRangeUnsigned
  adsvar: GVL_Checks.dCheckRangeUnsigned
  adstype: dint
 
######################## TESTOWE ZMIENNE ########################
 
- platform: ads
  name: Testowy int 0
  adsvar: P_System.iTestowy0
  adstype: int
- platform: ads
  name: Testowy int 1
  adsvar: P_System.iTestowy1
  adstype: int
- platform: ads
  name: Testowy int 2
  adsvar: P_System.iTestowy2
  adstype: int
- platform: ads
  name: Testowy int 3
  adsvar: P_System.iTestowy3
  adstype: int
- platform: ads
  name: Testowy int 4
  adsvar: P_System.iTestowy4
  adstype: int
- platform: ads
  name: Testowy int 5
  adsvar: P_System.iTestowy5
  adstype: int