
######################## LICZNIK WODY ########################

- platform: ads
  name: Woda Licznik TERAZ
  adsvar: GVL_Woda_HA.iWodaLicznikTERAZ
  unit_of_measurement: 'm³'
  factor: 1000
  adstype: dint
- platform: ads
  name: Woda Licznik zeszły miesiac
  adsvar: GVL_Woda_HA.iWodaLicznikZeszlyMiesiac
  unit_of_measurement: 'm³'
  adstype: dint
- platform: ads
  name: Woda Ogrod Licznik zeszły miesiac
  adsvar: GVL_Woda_HA.iWodaOgrodLicznikZeszlyMiesiac
  unit_of_measurement: 'm³'
  factor: 100
  adstype: dint

## PODSUMOWANIE RACHUNKU
- platform: ads
  name: Woda Aktualne użycie
  adsvar: GVL_Woda_HA.iWodaAktualnieUzycie
  unit_of_measurement: 'm³'
  factor: 100
  adstype: dint
- platform: ads
  name: Woda Aktualny rachunek
  adsvar: GVL_Woda_HA.iWodaAktualnieRachunek
  unit_of_measurement: 'zł'
  factor: 100
  adstype: dint

## PODSUMOWANIE RACHUNKU
- platform: ads
  name: Woda Zeszły miesiąc Uzycie
  adsvar: GVL_Woda_HA.iWodaZeszlyMiesiacUzycie
  unit_of_measurement: 'm³'
  adstype: int
- platform: ads
  name: Woda Zeszły miesiąc Rachunek
  adsvar: GVL_Woda_HA.iWodaZeszlyMiesiacRachunek
  unit_of_measurement: 'zł'
  factor: 100
  adstype: dint
- platform: ads
  name: Woda cena za 1m3
  adsvar: GVL_Woda_HA.iWodaCenaza1m3
  unit_of_measurement: 'PLN/m³'
  factor: 100
  adstype: int

 ######################## RACHUNEK ŚCIEKI ########################

## PODSUMOWANIE RACHUNKU
- platform: ads
  name: Scieki Aktualne użycie
  adsvar: GVL_Woda_HA.iSciekiAktualnieUzycie
  unit_of_measurement: 'm³'
  factor: 100
  adstype: dint
- platform: ads
  name: Scieki Aktualny rachunek
  adsvar: GVL_Woda_HA.iSciekiAktualnieRachunek
  unit_of_measurement: 'zł'
  factor: 100
  adstype: dint

## PODSUMOWANIE RACHUNKU
- platform: ads
  name: Scieki Zeszły miesiąc Uzycie
  adsvar: GVL_Woda_HA.iSciekiZeszlyMiesiacUzycie
  unit_of_measurement: 'm³'
  adstype: int
- platform: ads
  name: Scieki Zeszły miesiąc Rachunek
  adsvar: GVL_Woda_HA.iSciekiZeszlyMiesiacRachunek
  unit_of_measurement: 'zł'
  factor: 100
  adstype: dint
- platform: ads
  name: Scieki cena za 1m3
  adsvar: GVL_Woda_HA.iSciekiCenaza1m3
  unit_of_measurement: 'PLN/m³'
  factor: 100
  adstype: int

 ######################## WODA OGRODOWA ########################
- platform: ads
  name: Woda Ogrod miesiąc Uzycie
  adsvar: GVL_Woda_HA.iWodaOgrodAktualnieUzycie
  unit_of_measurement: 'm³'
  factor: 100
  adstype: dint

- platform: ads
  name: Woda Ogrod aktualnie rachunek
  adsvar: GVL_Woda_HA.iWodaOgrodAktualnieRachunek
  unit_of_measurement: 'zł'
  factor: 100
  adstype: dint

- platform: ads
  name: Woda Ogrod Zeszły miesiąc Uzycie
  adsvar: GVL_Woda_HA.iWodaOgrodZeszlyMiesiacUzycie
  unit_of_measurement: 'm³'
  factor: 10
  adstype: dint

- platform: ads
  name: Woda Ogrod Zeszły miesiąc Rachunek
  adsvar: GVL_Woda_HA.iWodaOgrodZeszlyMiesiacRachunek
  unit_of_measurement: 'zł'
  factor: 100
  adstype: dint

######################## TEMPERATURY ODCZYTANE PARTER ########################

- platform: ads
  name: Temp. ciepła woda
  adsvar: GVL_Ogrzewanie.iTEMP_WodaCiepla
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: Temp. cyrkulacja
  adsvar: GVL_Ogrzewanie.iTEMP_Cyrkulacja
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: Temp. cyrkulacja zadana
  adsvar: GVL_Ogrzewanie.iTEMP_CyrkulacjaZadana
  unit_of_measurement: '°C'
  factor: 10
  adstype: int

- platform: ads
  name: Woda ilosc obliczen   ## ilość wykonanych obliczeń w ciągu dnia
  adsvar: P_WaterMeter.iWodaCalc
  adstype: int

- platform: ads
  name: Scieki ilosc obliczen   ## ilość wykonanych obliczeń w ciągu dnia
  adsvar: P_WaterMeter.iSciekiCalc
  adstype: int
