
######################## POMIAR GAZU  ########################

## PODSUMOWANIE RACHUNKU

- platform: ads
  name: Gaz rachunek aktualnie
  adsvar: GVL_Gas_HA.iGazRachunekAktualny
  unit_of_measurement: 'zł'
  factor: 100
  adstype: dint

- platform: ads
  name: Gaz Dzisiejszy koszt za gaz
  adsvar: GVL_Gas_HA.iGazUzycieDzisiejszeKoszt
  unit_of_measurement: 'zł'
  factor: 100
  adstype: int

- platform: ads
  name: Gaz rachunek zeszły miesiąc
  adsvar: GVL_Gas_HA.iGazRachunekZeszlyMiesiac
  unit_of_measurement: 'zł'
  factor: 100
  adstype: dint

- platform: ads
  name: Gaz cena za 1m3
  adsvar: GVL_Gas_HA.iGazCenaZa1m3
  unit_of_measurement: 'PLN/m³'
  factor: 100
  adstype: int

## BIEŻĄCE UŻYCIE

- platform: ads
  name: Licznik główny gazu                 ## główna wartość licznika gazu
  adsvar: GVL_Gas_HA.iGazLicznikTERAZ
  unit_of_measurement: 'm³'
  factor: 100
  adstype: dint

- platform: ads
  name: Licznik główny gazu zeszły miesiac  ## główna wartość licznika gazu
  adsvar: GVL_Gas_HA.iGazLicznikZeszlyMiesiac
  unit_of_measurement: 'm³'
  adstype: dint

- platform: ads
  name: Zużycie gazu w tym dniu             ## zużycie w danym dniu
  adsvar: GVL_Gas_HA.iGazUzycieDzisiejsze
  unit_of_measurement: 'm³'
  factor: 100
  adstype: dint

- platform: ads
  name: Zużycie gazu w tym miesiacu         ## zużycie w danym miesiącu w m3
  adsvar: GVL_Gas_HA.iGazUzycieBiezace
  unit_of_measurement: 'm³'
  factor: 100
  adstype: dint

- platform: ads
  name: Zużycie gazu w zeszłym miesiacu     ## zużycie w poprzednim miesiącu
  adsvar: GVL_Gas_HA.iGazUzycieZeszlyMiesiac
  unit_of_measurement: 'm³'
#  factor: 100
  adstype: dint

######################## KOSZTY OBLICZENIA ########################

- platform: ads
  name: Licznik impulsów gaz PLC godzina   ## ilość impulsów w danej godzinie
  adsvar: P_GasMeter.impulsy_godzina
#  unit_of_measurement: 'impuls'
  adstype: int

- platform: ads
  name: Licznik impulsów gaz PLC dzien     ## ilość impulsów w danym dniu
  adsvar: P_GasMeter.impulsy_dzien
#  unit_of_measurement: 'impuls'
  adstype: int

- platform: ads
  name: Licznik impulsów gaz PLC miesiac   ## ilość impulsów w danym miesiacu
  adsvar: P_GasMeter.impulsy_miesiac
#  unit_of_measurement: 'impuls'
  adstype: int

- platform: ads
  name: Gaz ilosc obliczen   ## ilość wykonanych obliczeń w ciągu dnia
  adsvar: P_GasMeter.iGasCalc
  adstype: int
