
######################## TEMPERATURY ODCZYTANE PARTER ########################

- platform: ads
  name: Temp. Zasilanie P0
  adsvar: GVL_IO.iTemp_A3[5].bTemp
  unit_of_measurement: '°C'
  factor: 100 
  adstype: int
- platform: ads
  name: Temp. powrót P0
  adsvar: GVL_IO.iTemp_A3[7].bTemp
  unit_of_measurement: '°C'
  factor: 100 
  adstype: int
- platform: ads
  name: Temp. dogrzewacz IN
  adsvar: GVL_IO.iTemp_A3[3].bTemp
  unit_of_measurement: '°C'
  factor: 100 
  adstype: int
- platform: ads
  name: Temp. dogrzewacz OUT
  adsvar: GVL_IO.iTemp_A3[8].bTemp
  unit_of_measurement: '°C'
  factor: 100 
  adstype: int

- platform: ads
  name: Temp. Salon
  adsvar: GVL_Ogrzewanie.iTempHA_Salon
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: Temp. Kuchnia
  adsvar: GVL_Ogrzewanie.iTempHA_Kuchnia
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: Temp. Łazienka dolna
  adsvar: GVL_Ogrzewanie.iTempHA_LazienkaDolna
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: Temp. Gabinet
  adsvar: GVL_Ogrzewanie.iTempHA_Gabinet
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: Temp. Przedpokój wejściowy
  adsvar: GVL_Ogrzewanie.iTempHA_Przedpokoj
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: Temp. Spiżarka
  adsvar: GVL_Ogrzewanie.iTempHA_Spizarka
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: Temp. Garaż
  adsvar: GVL_Ogrzewanie.iTempHA_Garaz
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: Temp. Kotłownia
  adsvar: GVL_Ogrzewanie.iTempHA_Kotlownia
  unit_of_measurement: '°C'
  factor: 10
  adstype: int

############ TEMPERATURY ODCZYTANE PIĘTRO ############

- platform: ads
  name: Temp. zasilanie P1
  adsvar: GVL_IO.iTemp_A12[3].bTemp
  unit_of_measurement: '°C'
  factor: 100 
  adstype: int
- platform: ads
  name: Temp. powrót P1
  adsvar: GVL_IO.iTemp_A12[4].bTemp
  unit_of_measurement: '°C'
  factor: 100 
  adstype: int

- platform: ads
  name: Temp. Łazienka górna
  adsvar: GVL_Ogrzewanie.iTempHA_LazienkaGorna
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: Temp. Julia
  adsvar: GVL_Ogrzewanie.iTempHA_Julia
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: Temp. Oliwia
  adsvar: GVL_Ogrzewanie.iTempHA_Oliwia
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: Temp. Sypialnia
  adsvar: GVL_Ogrzewanie.iTempHA_Sypialnia
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: Temp. Biuro
  adsvar: GVL_Ogrzewanie.iTempHA_Biuro
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: Temp. Pralnia
  adsvar: GVL_Ogrzewanie.iTempHA_Pralnia
  unit_of_measurement: '°C'
  factor: 10
  adstype: int

######################## TEMPERATURY ZADANE PARTER ########################

- platform: ads
  name: TempSet. Salon
  adsvar: GVL_Ogrzewanie.iTEMPSet_Salon
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: TempSet. Kuchnia
  adsvar: GVL_Ogrzewanie.iTEMPSet_Kuchnia
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: TempSet. Łazienka dolna
  adsvar: GVL_Ogrzewanie.iTEMPSet_LazienkaDolna
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: TempSet. Gabinet
  adsvar: GVL_Ogrzewanie.iTEMPSet_Gabinet
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: TempSet. Spiżarka
  adsvar: GVL_Ogrzewanie.iTEMPSet_Spizarka
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: TempSet. Przedpokój wejściowy
  adsvar: GVL_Ogrzewanie.iTEMPSet_Przedpokoj
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: TempSet. Garaż
  adsvar: GVL_Ogrzewanie.iTEMPSet_Garaz
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: TempSet. Kotłownia
  adsvar: GVL_Ogrzewanie.iTempSet_Kotlownia
  unit_of_measurement: '°C'
  factor: 10
  adstype: int

######################## TEMPERATURY ZADANE PIĘTRO ########################

- platform: ads
  name: TempSet. Łazienka górna
  adsvar: GVL_Ogrzewanie.iTEMPSet_LazienkaGorna
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: TempSet. Julia
  adsvar: GVL_Ogrzewanie.iTEMPSet_Julia
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: TempSet. Oliwia
  adsvar: GVL_Ogrzewanie.iTEMPSet_Oliwia
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: TempSet. Sypialnia
  adsvar: GVL_Ogrzewanie.iTEMPSet_Sypialnia
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: TempSet. Biuro
  adsvar: GVL_Ogrzewanie.iTEMPSet_Biuro
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: TempSet. Pralnia
  adsvar: GVL_Ogrzewanie.iTEMPSet_Pralnia
  unit_of_measurement: '°C'
  factor: 10
  adstype: int

######################## TEMPERATURY PODŁOGI PARTER ########################
- platform: ads
  name: Podłoga Salon
  adsvar: GVL_Ogrzewanie.iPodloga_Salon
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: Podłoga Kuchnia
  adsvar: GVL_Ogrzewanie.iPodloga_Kuchnia
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: Podłoga Gabinet
  adsvar: GVL_Ogrzewanie.iPodloga_Gabinet
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: Podłoga LazienkaDolna
  adsvar: GVL_Ogrzewanie.iPodloga_LazienkaDolna
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: Podłoga Przedpokoj
  adsvar: GVL_Ogrzewanie.iPodloga_Przedpokoj
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: Podłoga Garaz
  adsvar: GVL_Ogrzewanie.iPodloga_Garaz
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: Podłoga Kotłownia
  adsvar: GVL_Ogrzewanie.iPodloga_Kotlownia
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: Podłoga Spiżarka
  adsvar: GVL_Ogrzewanie.iPodloga_Spizarka
  unit_of_measurement: '°C'
  factor: 10
  adstype: int

######################## TEMPERATURY PODŁOGI PIĘTRO ########################

- platform: ads
  name: Podłoga Sypialnia
  adsvar: GVL_Ogrzewanie.iPodloga_Sypialnia
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: Podłoga Garderoba
  adsvar: GVL_Ogrzewanie.iPodloga_Garderoba
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: Podłoga Pralnia
  adsvar: GVL_Ogrzewanie.iPodloga_Pralnia
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: Podłoga ŁazienkaGórna
  adsvar: GVL_Ogrzewanie.iPodloga_LazienkaGorna
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: Podłoga Oliwia
  adsvar: GVL_Ogrzewanie.iPodloga_Oliwia
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: Podłoga Julia
  adsvar: GVL_Ogrzewanie.iPodloga_Julia
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
- platform: ads
  name: Podłoga Biuro
  adsvar: GVL_Ogrzewanie.iPodloga_Biuro
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
