
######################## CZASY ZAŁĄCZONEJ PODŁOGÓWKI ########################

- platform: history_stats
  name: CirculationPomp Time_ON
  entity_id: binary_sensor.pompa_cyrkulacji
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: CirculationPomp Count_ON
  entity_id: binary_sensor.pompa_cyrkulacji
  state: 'on'
  type: count
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'  

######################## PIEC VAILLANT ########################

- platform: history_stats
  name: vaillant unavailable_time
  entity_id: binary_sensor.nasznowydom_online_status
  state: 'unavailable'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: vaillant unavailable_count
  entity_id: binary_sensor.nasznowydom_online_status
  state: 'unavailable'
  type: count
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'  
  
- platform: history_stats
  name: vaillant offline_time
  entity_id: binary_sensor.nasznowydom_online_status
  state: 'offline'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: vaillant offline_count
  entity_id: binary_sensor.nasznowydom_online_status
  state: 'offline'
  type: count
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'  
