
######################## GŁÓWNE WŁĄCZNIKI ŚWIATEŁ ########################

  # wyłącz wszystkie światła
- platform: ads
  name: Wyłącz wszystkie światła
  adsvar: GVL_Oswietlenie.bAllLightTurnOFF

  # załącz wszystkie światła
- platform: ads
  name: Włącz wszystkie światła
  adsvar: GVL_Oswietlenie.bAllLightTurnON
