 ######################## AKTYWACJA ŻALUZJI ########################

- platform: ads
  name: blinds_on_1
  adsvar: GVL_Zaluzje.Zaluzje[1].Aktywna
- platform: ads
  name: blinds_on_2
  adsvar: GVL_Zaluzje.Zaluzje[2].Aktywna
- platform: ads
  name: blinds_on_3
  adsvar: GVL_Zaluzje.Zaluzje[3].Aktywna
- platform: ads
  name: blinds_on_4
  adsvar: GVL_Zaluzje.Zaluzje[4].Aktywna
- platform: ads
  name: blinds_on_5
  adsvar: GVL_Zaluzje.Zaluzje[5].Aktywna
- platform: ads
  name: blinds_on_6
  adsvar: GVL_Zaluzje.Zaluzje[6].Aktywna
- platform: ads
  name: blinds_on_7
  adsvar: GVL_Zaluzje.Zaluzje[7].Aktywna
- platform: ads
  name: blinds_on_8
  adsvar: GVL_Zaluzje.Zaluzje[8].Aktywna
- platform: ads
  name: blinds_on_9
  adsvar: GVL_Zaluzje.Zaluzje[9].Aktywna
- platform: ads
  name: blinds_on_10
  adsvar: GVL_Zaluzje.Zaluzje[10].Aktywna

######################## ŻALUZJE CALY DOM ########################

- platform: ads
  name: blinds_all_down
  adsvar: GVL_Zaluzje.Dom_wDol
- platform: ads
  name: blinds_all_up
  adsvar: GVL_Zaluzje.Dom_wGore
- platform: ads
  name: blinds_all_close
  adsvar: GVL_Zaluzje.Dom_Zamknij
- platform: ads
  name: blinds_all_lms_down
  adsvar: GVL_Zaluzje.Dom_Lamelki_wDol
- platform: ads
  name: blinds_all_lms_up
  adsvar: GVL_Zaluzje.Dom_Lamelki_wGore

######################## ŻALUZJE PARTER ########################

- platform: ads
  name: blinds_p0_down
  adsvar: GVL_Zaluzje.Parter_wDol
- platform: ads
  name: blinds_p0_up
  adsvar: GVL_Zaluzje.Parter_wGore
- platform: ads
  name: blinds_p0_close
  adsvar: GVL_Zaluzje.Parter_Zamknij
- platform: ads
  name: blinds_p0_lms_down
  adsvar: GVL_Zaluzje.Parter_Lamelki_wDol
- platform: ads
  name: blinds_p0_lms_up
  adsvar: GVL_Zaluzje.Parter_Lamelki_wGore

######################## ŻALUZJE PIETRO ########################

- platform: ads
  name: blinds_p1_down
  adsvar: GVL_Zaluzje.Pietro_wDol
- platform: ads
  name: blinds_p1_up
  adsvar: GVL_Zaluzje.Pietro_wGore
- platform: ads
  name: blinds_p1_close
  adsvar: GVL_Zaluzje.Pietro_Zamknij
- platform: ads
  name: blinds_p1_lms_down
  adsvar: GVL_Zaluzje.Pietro_Lamelki_wDol
- platform: ads
  name: blinds_p1_lms_up
  adsvar: GVL_Zaluzje.Pietro_Lamelki_wGore
