
######################## ZAWORY WODY ########################

- platform: ads
  name: ZaworWody_1_Otworz
  adsvar: GVL_Zawory.ZaworWody_1_Otworz
- platform: ads
  name: ZaworWody_1_Zamknij
  adsvar: GVL_Zawory.ZaworWody_1_Zamknij

- platform: ads
  name: ZaworWody_2_Otworz
  adsvar: GVL_Zawory.ZaworWody_2_Otworz
- platform: ads
  name: ZaworWody_2_Zamknij
  adsvar: GVL_Zawory.ZaworWody_2_Zamknij

- platform: ads
  name: ZaworWody_3_Otworz
  adsvar: GVL_Zawory.ZaworWody_3_Otworz
- platform: ads
  name: ZaworWody_3_Zamknij
  adsvar: GVL_Zawory.ZaworWody_3_Zamknij

- platform: ads
  name: Reset czujnikow zalania
  adsvar: P_Kotlownia.CzujnikiZalania_Reset

- platform: ads
  name: Pompa cyrkulacji wymuszenie
  adsvar: P_Kotlownia.CWU_WymuszenieCyrkulacji

- platform: ads
  name: Mostek czujnikow zalania
  adsvar: P_Kotlownia.CzujnikiZalania_Mostek

