
######################## BRAMY I FURTKI ########################

  # dzwonek włączony
- platform: ads
  name: Dzwonek
  adsvar: GVL_Gniazdka.DzwonekZezwolenie

  # furtka otwarcie
- platform: ads
  name: Furtka zewnętrzna
  adsvar: P_BramyFurtki.Furtka_HMI

  # brama garażowa
- platform: ads
  name: Brama garażowa SBS
  adsvar: P_BramyFurtki.BramaGarazowa_HMI

  # brama wjazdowa 
- platform: ads
  name: Brama wjazdowa SBS
  adsvar: P_BramyFurtki.BramaWjazdowa_HMI

- platform: ads
  name: Brama i furtka mostek
  adsvar: GVL_Alarm.bPhoneBridge

- platform: ads
  name: Furtka MostekTymczasowy
  adsvar: GVL_Bramy_Furtki.MostekTymczasowy
