
######################## GNIAZDKA 230v ########################

- platform: ads
  name: Kotłownia dogrzewacz 1
  adsvar: GVL_Gniazdka.Q_PS_Dogrzewacz_1
- platform: ads
  name: Kotłownia dogrzewacz 2
  adsvar: GVL_Gniazdka.Q_PS_Dogrzewacz_2
- platform: ads
  name: Kaloryfer łazienka górna
  adsvar: GVL_Gniazdka.Q_PS_bathroomUP_Radiator
- platform: ads
  name: Wentylator łazienka górna
  adsvar: GVL_Gniazdka.Q_PS_bathroomUP_fan
- platform: ads
  name: Kaloryfer łazienka dolna
  adsvar: GVL_Gniazdka.Q_PS_bathroomDWN_Radiator
- platform: ads
  name: Gniazdka TV Sypialnia
  adsvar: GVL_Gniazdka.Q_PS_badroom_TV
- platform: ads
  name: Gniazdka TV Oliwia
  adsvar: GVL_Gniazdka.Q_PS_oliwia_TV
- platform: ads
  name: Gniazdka TV Julia
  adsvar: GVL_Gniazdka.Q_PS_julia_TV
- platform: ads
  name: Gniazdka TV Biuro
  adsvar: GVL_Gniazdka.Q_PS_office_TV
- platform: ads
  name: Gniazdka pralnia 1
  adsvar: GVL_Gniazdka.Q_PS_washroom_GN1
- platform: ads
  name: Gniazdka pralnia 2
  adsvar: GVL_Gniazdka.Q_PS_washroom_GN2
- platform: ads
  name: Gniazdka łazienka
  adsvar: GVL_Gniazdka.Q_PS_bathroomUP_GN1
- platform: ads
  name: Gniazdka przedpokoj
  adsvar: GVL_Gniazdka.Q_PS_entranceHall
- platform: ads
  name: Gniazdka zewnętrzne
  adsvar: GVL_Gniazdka.Q_PS_Outsite
- platform: ads
  name: Gniazdka pompa 
  adsvar: GVL_Gniazdka.Q_PS_Outsite_2
- platform: ads
  name: Gniazdka zewnetrzne pietro 
  adsvar: GVL_Gniazdka.Q_PS_Outsite_Up
- platform: ads
  name: Gniazdka salon
  adsvar: GVL_Gniazdka.Q_PS_salon
- platform: ads
  name: Gniazdka TV salon
  adsvar: GVL_Gniazdka.Q_PS_salon_TV
- platform: ads
  name: Gniazdka strych
  adsvar: GVL_Gniazdka.Q_PS_Attic

- platform: ads
  name: Tryb BASEN
  adsvar: GVL_Gniazdka.bTrybBasen