
######################## ŻALUZJE ########################

- platform: ads
  name: blinds_all_up
  device_class: moving
  adsvar: P_Zaluzje.bAllUpPos
- platform: ads
  name: blinds_all_down
  device_class: moving
  adsvar: P_Zaluzje.bAllDwnPos
  
- platform: ads
  name: blinds_p0_up
  device_class: moving
  adsvar: P_Zaluzje.bP0UpPos
- platform: ads
  name: blinds_p0_dwn
  device_class: moving
  adsvar: P_Zaluzje.bP0DwnPos
  
- platform: ads
  name: blinds_p1_up
  device_class: moving
  adsvar: P_Zaluzje.bP1UpPos
- platform: ads
  name: blinds_p1_dwn
  device_class: moving
  adsvar: P_Zaluzje.bP1DwnPos


- platform: ads
  name: blinds_lms_all_up
  device_class: moving
  adsvar: P_Zaluzje.bAllLmsUpPos
- platform: ads
  name: blinds_lms_all_down
  device_class: moving
  adsvar: P_Zaluzje.bAllLmsDwnPos
  
- platform: ads
  name: blinds_lms_p0_up
  device_class: moving
  adsvar: P_Zaluzje.bP0LmsUpPos
- platform: ads
  name: blinds_lms_p0_dwn
  device_class: moving
  adsvar: P_Zaluzje.bP0LmsDwnPos
  
- platform: ads
  name: blinds_lms_p1_up
  device_class: moving
  adsvar: P_Zaluzje.bP1LmsUpPos
- platform: ads
  name: blinds_lms_p1_dwn
  device_class: moving
  adsvar: P_Zaluzje.bP1LmsDwnPos
