
######################## ZASILANIE SIECIOWEJ OK ########################

- platform: ads
  name: Zasilanie 230v OK
  device_class: safety
  adsvar: GVL_Power.HA_Zasilanie_OK
  
######################## BEZPIECZNIKI 24V ########################

- platform: ads
  name: bezpiecznik_p0_rezerwa
  adsvar: GVL_Power.HA_bezpiecznik_P0_1
  device_class: safety
- platform: ads
  name: bezpiecznik_p0_wykonawcze
  adsvar: GVL_Power.HA_bezpiecznik_P0_2
  device_class: safety
- platform: ads
  name: bezpiecznik_p0_przelaczniki
  adsvar: GVL_Power.HA_bezpiecznik_P0_3
  device_class: safety
- platform: ads
  name: bezpiecznik_p0_zewnetrzne
  adsvar: GVL_Power.HA_bezpiecznik_P0_4
  device_class: safety
- platform: ads
  name: bezpiecznik_p0_wykonawcze_pietro
  adsvar: GVL_Power.HA_bezpiecznik_P0_5
  device_class: safety
  
- platform: ads
  name: bezpiecznik_p1_czujnik_zalania
  adsvar: GVL_Power.HA_bezpiecznik_P1_1
  device_class: safety
- platform: ads
  name: bezpiecznik_p1_wykonawcze
  adsvar: GVL_Power.HA_bezpiecznik_P1_2
  device_class: safety
- platform: ads
  name: bezpiecznik_p1_przelaczniki
  adsvar: GVL_Power.HA_bezpiecznik_P1_3
  device_class: safety
- platform: ads
  name: bezpiecznik_p1_zewnetrzne
  adsvar: GVL_Power.HA_bezpiecznik_P1_4
  device_class: safety
- platform: ads
  name: bezpiecznik_p1_rezerwa
  adsvar: GVL_Power.HA_bezpiecznik_P1_5
  device_class: safety
