
######################## CZUJNIKI RUCHU PARTER ########################

- platform: ads
  name: Ruch Salon
  device_class: motion
  adsvar: GVL_CzujnikiRuchu.HA_Salon
- platform: ads
  name: Ruch Kuchnia
  device_class: motion
  adsvar: GVL_CzujnikiRuchu.HA_Kuchnia
- platform: ads
  name: Ruch Gabinet
  device_class: motion
  adsvar: GVL_CzujnikiRuchu.HA_Gabinet
- platform: ads
  name: Ruch Łazienka dolna
  device_class: motion
  adsvar: GVL_CzujnikiRuchu.HA_LazienkaParter
- platform: ads
  name: Ruch Korytarz dolny
  device_class: motion
  adsvar: GVL_CzujnikiRuchu.HA_KorytarzParter
- platform: ads
  name: Ruch Garderoba przedpokój
  device_class: motion
  adsvar: GVL_CzujnikiRuchu.HA_GarderobaParter
- platform: ads
  name: Ruch Przedpokoj
  device_class: motion
  adsvar: GVL_CzujnikiRuchu.HA_Przedpokoj
- platform: ads
  name: Ruch Garaż
  device_class: motion
  adsvar: GVL_CzujnikiRuchu.HA_Garaz
- platform: ads
  name: Ruch Kotłownia
  device_class: motion
  adsvar: GVL_CzujnikiRuchu.HA_Kotlownia
- platform: ads
  name: Ruch Spiżarka
  device_class: motion
  adsvar: GVL_CzujnikiRuchu.HA_Spizarka 

######################## CZUJNIKI RUCHU PIĘTRO ########################

- platform: ads
  name: Ruch Sypialnia
  device_class: motion
  adsvar: GVL_CzujnikiRuchu.HA_Sypialnia
- platform: ads
  name: Ruch Garderoba sypialnia
  device_class: motion
  adsvar: GVL_CzujnikiRuchu.HA_GarderobaPietro
- platform: ads
  name: Ruch Łazienka górna
  device_class: motion
  adsvar: GVL_CzujnikiRuchu.HA_LazienkaPietro
- platform: ads
  name: Ruch Julia
  device_class: motion
  adsvar: GVL_CzujnikiRuchu.HA_Julia
- platform: ads
  name: Ruch Oliwia
  device_class: motion
  adsvar: GVL_CzujnikiRuchu.HA_Oliwia
- platform: ads
  name: Ruch Biuro
  device_class: motion
  adsvar: GVL_CzujnikiRuchu.HA_Biuro
- platform: ads
  name: Ruch Korytarz górny
  device_class: motion
  adsvar: GVL_CzujnikiRuchu.HA_KorytarzPietro
- platform: ads
  name: Ruch Pralnia
  device_class: motion
  adsvar: GVL_CzujnikiRuchu.HA_Pralnia

######################## CZUJNIKI RUCHU STRYCH ########################

- platform: ads
  name: Ruch Strych_1
  device_class: motion
  adsvar: GVL_CzujnikiRuchu.HA_Strych1
- platform: ads
  name: Ruch Strych_2
  device_class: motion
  adsvar: GVL_CzujnikiRuchu.HA_Strych2

