
######################## CZUJNIKI ZALANIA PARTER ########################

- platform: ads
  name: Czujnik zalania parter
  adsvar: GVL_Woda_HA.HA_CzujnikiZalania_Parter
  device_class: safety  
- platform: ads
  name: Wykryto zalanie parter
  adsvar: GVL_Woda.WykryteZalanie_Parter
  device_class: problem

######################## CZUJNIKI ZALANIA PIĘTRO ########################

- platform: ads
  name: Czujnik zalania pietro
  adsvar: GVL_Woda_HA.HA_CzujnikiZalania_Pietro
  device_class: safety
- platform: ads
  name: Wykryto zalanie piętro
  adsvar: GVL_Woda.WykryteZalanie_Pietro
  device_class: problem

######################## POMA CYRKULACJI ########################

- platform: ads
  name: Pompa cykulacji automat
  adsvar: P_Kotlownia.fb_PompaCyrkulacji.bLd
  device_class: plug  

- platform: ads
  name: Zezwolenie na uruchomienie pompy
  adsvar: P_Kotlownia.PompaCyrkulacji_Zezwolenie

######################## PRALKA, SUSZARKAI PRALNIA ########################

- platform: ads
  name: Pralka1
  adsvar: P_Kotlownia.bWashing1
- platform: ads
  name: Pranie1 oczekiwanie
  adsvar: P_Kotlownia.bWashingWaiting1
- platform: ads
  name: Pralka2
  adsvar: P_Kotlownia.bWashing2
- platform: ads
  name: Pranie2 oczekiwanie
  adsvar: P_Kotlownia.bWashingWaiting2
- platform: ads
  name: Suszarka
  adsvar: P_Kotlownia.bDryMachine
- platform: ads
  name: Suszarka oczekiwanie
  adsvar: P_Kotlownia.bDryMachineWaiting

######################## ZMYWARKA NACZYŃ ########################

- platform: ads
  name: Zmywarka
  adsvar: P_Kotlownia.bDishMachine
- platform: ads
  name: Zmywarka oczekiwanie
  adsvar: P_Kotlownia.bDishMachineWaiting


