
######################## SKRZYNKA NA LISTY ######################## 

- platform: ads
  name: List w skrzynce
  adsvar: P_BramyFurtki.SkrzynkaNaListy_List
- platform: ads
  name: Skrzynka na listy zewn
  device_class: opening
  adsvar: GVL_Bramy_Furtki.HA_SkrzynkaNaList_IN
- platform: ads
  name: Skrzynka na listy wewn
  device_class: opening
  adsvar: GVL_Bramy_Furtki.HA_SkrzynkaNaList_OUT
    
######################## FURTKA WEJSCIOWA ######################## 
 
- platform: ads
  name: Furtka wejściowa
  device_class: door
  adsvar: GVL_Bramy_Furtki.HA_FurtkaWejsciowa

- platform: ads
  name: Furtka elektrozamek
  device_class: lock
  adsvar: P_BramyFurtki.Furtka_Elektrozamek
- platform: ads
  name: Furtka zezwolenie
  device_class: lock
  adsvar: P_BramyFurtki.Furtka_Zezwolenie

######################## FURTKA SMIECI ZEWNETRZNA ########################  

- platform: ads
  name: Furtka śmieci zewnętrzna
  device_class: door
  adsvar: GVL_Bramy_Furtki.HA_FurtkaSmieci_zewnetrzna

######################## FURTKA SMIECI WEWNETRZNA ########################  

- platform: ads
  name: Furtka śmieci wewnętrzna
  device_class: door
  adsvar: GVL_Bramy_Furtki.HA_FurtkaSmieci_wewnetrzna

- platform: ads
  name: FurtkaSmieci zezwolenie
  adsvar: P_BramyFurtki.HA_FurtkaSmieci_Zezwolenie

