
######################## CZUJNIKI OKIEN PARTER ######################## 

- platform: ads
  name: window_salon_taras
  device_class: door
  adsvar: GVL_Okna.Taras
- platform: ads
  name: window_salon_l
  device_class: window
  adsvar: GVL_Okna.Salon_L
- platform: ads
  name: window_salon_r
  device_class: window
  adsvar: GVL_Okna.Salon_R
- platform: ads
  name: window_kitchen_l
  device_class: window
  adsvar: GVL_Okna.Kuchnia_L
- platform: ads
  name: window_kitchen_r
  device_class: window
  adsvar: GVL_Okna.Kuchnia_R
- platform: ads
  name: window_smallroom_l
  device_class: window
  adsvar: GVL_Okna.Gabinet_L
- platform: ads
  name: window_smallroom_R
  device_class: window
  adsvar: GVL_Okna.Gabinet_R
- platform: ads
  name: window_bathroom_down
  device_class: window
  adsvar: GVL_Okna.LazienkaDolna
- platform: ads
  name: window_entrance
  device_class: window
  adsvar: GVL_Okna.Przedpokoj

######################## CZUJNIKI OKIEN PIĘTRO ########################

- platform: ads
  name: window_badroom_l
  device_class: window
  adsvar: GVL_Okna.Sypialnia_L
- platform: ads
  name: window_badroom_r
  device_class: window
  adsvar: GVL_Okna.Sypialnia_R
- platform: ads
  name: window_bathroom_up
  device_class: window
  adsvar: GVL_Okna.LazienkaGorna
- platform: ads
  name: window_julia_l
  device_class: window
  adsvar: GVL_Okna.Julia_L
- platform: ads
  name: window_julia_r
  device_class: window
  adsvar: GVL_Okna.Julia_R
- platform: ads
  name: window_oliwia_l
  device_class: window
  adsvar: GVL_Okna.Oliwia_L
- platform: ads
  name: window_oliwia_r
  device_class: window
  adsvar: GVL_Okna.Oliwia_R
- platform: ads
  name: window_office_l
  device_class: window
  adsvar: GVL_Okna.Biuro_L
- platform: ads
  name: window_office_r
  device_class: window
  adsvar: GVL_Okna.Biuro_R
- platform: ads
  name: window_washroom
  device_class: window
  adsvar: GVL_Okna.Pralnia
