
######################## SYSTEMOWE ########################

- platform: ads
  name: alwaystrue
  adsvar: GVL.bTrue
  
- platform: ads
  name: Ring_button
  adsvar: P_BramyFurtki.bDzwonek_Przycisk

- platform: ads
  name: Slonce_full
  adsvar: P_System.bSlonecznie
  device_class: light  

- platform: ads
  name: Brak wiatru 60m
  adsvar: P_System.bBrakWiatru_60m
- platform: ads
  name: Brak wiatru 10m
  adsvar: P_System.bBrakWiatru_10m
- platform: ads
  name: Brak wiatru 2m
  adsvar: P_System.bBrakWiatru_2m

- platform: ads
  name: Testowy bool 1
  adsvar: P_SYSTEM.bTestowy1
