
######################## GŁÓWNE CZUJNIKI DOMU ########################

- platform: ads
  name: Czujnik gazu impuls
  adsvar: GVL_Gas.bGasMeter_imp
  
- platform: ads
  name: Czujnik gazu wykryto otwarcie
  adsvar: GVL_Gas.CzujnikOtwarcia_Wykrycie
