
######################## ZEZWOLENIE NA URUCHOMIENIE GNIAZDEK ########################

- platform: ads
  name: Zezwolenie na media parter
  device_class: power
  adsvar: P_Gniazdka_P0.bRelease
  
- platform: ads
  name: Zezwolenie na media pietro
  device_class: power
  adsvar: P_Gniazdka_P1.bRelease
